#!/bin/bash

AUTHORIZED_KEYS = "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAykiiTgWKSpE9PL3+YeQEa6E/oMaPV/3cvKH78q+emSsC/SqA9Z2OvfdeIdApDaHY3SM8ENNB6Uwd8ajoSRe2kPh+KcfXxW2M6HneWK4hT50Q5Y4ArO66awL8tYSGJhFEtg01G0TuuwIbbNgfDdW8UfisZCVVyYpmBuDKsfIqtpHgyFY1Z+7AQwcRBAsRwIquQPMgzi9340SAv0fk++ufh643QUCA1qlc8i+lGrZuJ1blybdpf/RczO3nCNnqW2qtQSM9kizn31u3uuCZ8ENtJVw4V+ooAaIhdkmJEk9T99sOvusO2dpR28m/7cjGiJYl/VfHUyW48w18TLtJvmJrWQ== root@localhost.localdomain"

if [ "${AUTHORIZED_KEYS}" != "**None**" ]; then
    echo "=> Found authorized keys"
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    touch /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    IFS=$'\n'
    arr=$(echo ${AUTHORIZED_KEYS} | tr "," "\n")
    for x in $arr
    do
        x=$(echo $x |sed -e 's/^ *//' -e 's/ *$//')
        cat /root/.ssh/authorized_keys | grep "$x" >/dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "=> Adding public key to /root/.ssh/authorized_keys: $x"
            echo "$x" >> /root/.ssh/authorized_keys
        fi
    done
fi

if [ -f /.root_pw_set ]; then
	echo "Root password already set!"
	exit 0
fi

PASS=${ROOT_PASS}
_word=$( [ ${ROOT_PASS} ] && echo "preset" || echo "random" )
echo "=> Setting a ${_word} password to the root user"
echo "root:$PASS" | chpasswd

echo "=> Done!"
touch /.root_pw_set

echo "========================================================================"
echo "You can now connect to this CentOS container via SSH using:"
echo ""
echo "    ssh -p <port> root@<host>"
echo "and enter the root password '$PASS' when prompted"
echo ""
echo "Please remember to change the above password as soon as possible!"
echo "========================================================================"
